### ISSUE TITLE
Taplist/Admin Panel Cannot Accept Some Unicode

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#105]
I added the new styles and they look like they're working.

Unfortunately, it breaks on some unicode characters (which seem to be mostly German characters this time).

On the front page:

![untitled](https://f.cloud.github.com/assets/6320180/2095721/60e60dbc-8eee-11e3-8404-7419ace88b98.png)

On the admin panel:

![untitled](https://f.cloud.github.com/assets/6320180/2095723/6fe32df4-8eee-11e3-975a-b5f62c0cd963.png)

I'm assuming this will be used by non-English speakers that will want their native characters.

Is this an easy fix, or a huge compatibility issue?

**Comment by JayUnt** [comment]
The problem is with those chars not being html encoded.  But the proper way to put those characters in the db is to use the html encoded versions.  When we do an db insert from the admin screens, we automatically convert them. But since this was a straight insert through the schema.sql, we didnt.

I updated the two that were in the image, take a look and update any others that might be an issue.  They actually looked fine on my screen, so I can't really test.  You can use this site as a reference for the codes. 

http://www.degraeve.com/reference/specialcharacters.php

**Comment by thadius856** [comment]
I see what you did here.

Looks like you added tildes to Kolsch and Oktoberfest/Marzen. I've changed these to umlats. You also missed Dusseldorf Altbier, so I've fixed that one too.

Unfortunately, it fixes the Front Page, but doesn't render correctly in the dropdown.

Sauce:

![untitled](https://f.cloud.github.com/assets/6320180/2117335/a0d13864-90c6-11e3-8c74-1e68ab212587.png)

![untitled](https://f.cloud.github.com/assets/6320180/2117340/f4677a88-90c6-11e3-9df9-98036ce36653.png)

![untitled](https://f.cloud.github.com/assets/6320180/2117342/07704344-90c7-11e3-8e93-17de3ac40ce4.png)

Ideas?

**Comment by JayUnt** [comment]
see if that works.  Unfortunately im still not seeing the issue, but the fix makes sense to me.

**Comment by thadius856** [comment]
Tested, looks great now.

Closing as fixed.
