### ISSUE TITLE
Website: Styling and Layout

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#60]
Continued from #31.

Created a GitHub Pages account and basic page. The url is:

http://raspberrypints.github.io/RaspberryPints/

Unfortunately, their generator only spits out a single page. Luckily for us, it creates the site in the `gh-pages` branch, so we can upload basically anything we want there. Custom images/CSS, as many pages as we like, etc.

It's been about 10 years since I built a site. Back then it was with notepad and I remember the time commitment.

Would like to use an editor or template this time for a basic front page plus 4-5 pages. Pretty overwhelmed with choices. Any input?

**Comment by Skemp45** [comment]
ok, I took the files from pages and created them into the wordpress theme and installed wordpress and added that theme. here is what we have. 
http://raspberrypints.com/site/

**Comment by thadius856** [comment]
You asshole! I spent like 6 hours researching how to do this, and you can make it happen with a snap of the fingers. So jealous right now. >:\

But really, it's pretty schweet. Does this mean we're paying for hosting somewhere?

Also, how does one go about getting access to start building this site? :D

**Comment by Skemp45** [comment]
I have hosting for other sites forever lol so I can host it. and let me make you a wordpress login for it

**Comment by Skemp45** [comment]
raspberrypints is your user and your password was sent to your email
login is http://raspberrypints.com/site/wp-admin

**Comment by thadius856** [comment]
Been futzing around a bit. Think I have my feel of the land now.

When you get a chance, can you load this (or similar) plugin? I'm afraid I'll jack it all up if I do it. :)

http://wordpress.org/plugins/subpage-listing/

**Comment by thadius856** [comment]
Oh, woah, nvm. Easier than I thought. Installed it myself in about 10 seconds. :)

**Comment by Skemp45** [comment]
I am pretty good with wordpress so go wild I can normally undo just about anything.

**Comment by Skemp45** [comment]
site is coming along great

**Comment by thadius856** [comment]
Writing content always sucks ass. :\

**Comment by Skemp45** [comment]
THE WORST hahah

**Comment by thadius856** [comment]
Question with this Responsive template.

Is there some tag I can use like a pre box... yanno, like [code][/code] or similar?

**Comment by Skemp45** [comment]
[nbox type="notice"]    Script goes here [/nbox]

**Comment by Skemp45** [comment]
http://raspberrypints.com/site/test-script-box/

**Comment by Skemp45** [comment]
you can delete page after you look

**Comment by thadius856** [comment]
Very nice. _yoink_

**Comment by Skemp45** [comment]
http://raspberrypints.com/site/wp-admin/options-general.php?page=noticeboxes

**Comment by Skemp45** [comment]
all the different ones. Its a plugin I use all the time

**Comment by Skemp45** [comment]
If you have any questions on the wordpress stuff let me know I will help.

**Comment by Skemp45** [comment]
http://www.amazon.com/Raspberry-Ultimate-Includes-Essential-Accessories/dp/B00CXACPN0/ref=sr_1_1?ie=UTF8&qid=1390274307&sr=8-1&keywords=Raspberry+Pi+Ultimate+Starter+Kit+--+Includes+Raspberry+Pi+Board+%2B+11+Essential+Accessories

maybe we should suggest users to buy this

**Comment by thadius856** [comment]
We could. Couple problems with that kit, though.
1. The 4gb SD card is almost certainly Class 4. Raspberry Pi operates at less than half speed on a Class 4 card. Class 10 or Ultra 1 all the way.
2. That WiFi card uses a shitty old RealTek chipset. These cards are $2-3 shipped on eBay. I have a similar card based on this same chipset. I get poor reception and tons of dropouts with it, and it gets quite warm.
3. I can't think of any reason they'd need to go GPIO to USB cable, ribbon cable, breadboard, breadboard jumper wires, or breakout card.
4. It's about the same price for nice components.

Pi = $41
Charger (1500 ma) = $10
WiFi (RTL8188CUS chipset) = $10
SD (16gb Ultra 1) = $13
HDMI cable (6') = $5.
TOTAL = $79

**Comment by Skemp45** [comment]
pi-http://www.amazon.com/RASPBERRY-MODEL-756-8308-Raspberry-Pi/dp/B009SQQF9C/ref=sr_1_1?s=electronics&ie=UTF8&qid=1390274999&sr=1-1&keywords=raspberry+pi

Charger- http://www.amazon.com/gp/product/B00DZLSEVI/ref=ox_sc_act_title_1?ie=UTF8&psc=1&smid=AYY3UP8OL9FV8

wifi- http://www.amazon.com/EW-7811UN-IEEE-802-11n-draft-USB/dp/B005CLMJLU/ref=sr_1_1?ie=UTF8&qid=1390274952&sr=8-1&keywords=RTL8188CUS+chipset

sd- http://www.amazon.com/SanDisk-Ultra-Class-Memory-SDSDU-016G-U46/dp/B007BJHETS/ref=sr_1_2?s=electronics&ie=UTF8&qid=1390275044&sr=1-2&keywords=SD+%2816gb+Ultra+1%29

???
case- http://www.amazon.com/Raspberry-Model-Protective-Special-Weekend/dp/B00C5OU3PQ/ref=sr_1_15?s=electronics&ie=UTF8&qid=1390275072&sr=1-15&keywords=raspberry+pi+case

**Comment by Skemp45** [comment]
that work?
Im going to buy my stuff tonight

**Comment by thadius856** [comment]
Pi, yes.
Charger, yes.
WiFi, yes.
SD, yes.

Case... meh. I prefer this one: http://www.amazon.com/Raspberry-Pi-Case-Enclosure-Clear/dp/B0097NPQ8W/ref=sr_1_2?s=electronics&ie=UTF8&qid=1390275273&sr=1-2&keywords=clear+pi+case

You don't have a 700ma or higher micro USB phone charger laying around?

Did you remember the SD card reader and the HDMI cable?

**Comment by thadius856** [comment]
Just wrote this all up on the website, btw: http://raspberrypints.com/site/byo/preparation/

**Comment by Skemp45** [comment]
my laptop has a sd reader and about a year ago I bought a liquidation sale of over 100 hdmi cables......... DONT ASK I thought it was a good idea

**Comment by thadius856** [comment]
Hah. I know a guy that buys 10-pks on eBay from China, then sells em for $5-7 ea on CraigsList from his front door.

**Comment by thadius856** [comment]
We'll have some new help, soon.

kerber is interested in helping write the GPIO code.
sloescher is interested in helping write the install instructions.
raysmithtx is interested in helping spruce up the layout/colors/etc of the website.

Chugging along!

**Comment by raysmithtx** [comment]
I don't have access to the existing website yet but have put together a test site to show kind of the direction I am thinking for the website. Will need images and text as they become available. Just want to get some feedback at this point. Test site is located at http://rays-sites3.com. Please give me some feedback.

**Comment by thadius856** [comment]
I like what you've tried here. Can we keep close-ish to the Responsive
theme plugin we have installed on the existing site?

Skemp, can you get him access to be able to work with the pages? I'm in the
middle of something this morning, but if you can't get to it this morning,
I'll try later this afternoon.

**Comment by Skemp45** [comment]
Hello Ray, 

Sorry I have been sick all week and forgot to add your ughh my bad, here it is

User: raysmithtx
Password was emailed to raysmithtx@sbcglobal.net
login url is 
http://raspberrypints.com/site/wp-admin

Sorry again for the lateness of this!!!

**Comment by Skemp45** [comment]
Thad, 

do you use the raspberrypints user at all? 
If not I am going to remove it. No use in having an extra admin user!

**Comment by thadius856** [comment]
Skemp,

I don't currently use it, but I've gotten in the habit over the years of keeping a spare admin account on hand with a different password for emergencies. For mission critical systems, a second spare even.

You'd have no idea how many times it's saved my ass.

**Comment by Skemp45** [comment]
hahah ok, no problemo I will leave it

**Comment by raysmithtx** [comment]
For people like me who like printed pages I added Print and PDF options at the bottom of all pages. Allows user to select exactly what and how they want to print or allows them to save the page as a PDF file.

**Comment by thadius856** [comment]
See, I would never have thought of that.

**Comment by Skemp45** [comment]
Shawn Kemp [Liked] This

**Comment by jkurl** [comment]
Thadius,

I have a nice word template that could be used to the how to instructions.  I took a look at V2 that was on Homebrewtalk forum. looks nice and development on it is coming along nicely. I use this template for course design and can take what has been done and convert it over to this nice and neat layout.  if you, the person developing the instructions and team would be willing to let me help you guys out. once it is all done I will provide you the master word doc which can be edited and then converted to a PDF. 

Jerry

Mod edit (Thadius 26 Jan 14): removed leading tab so GH doesn't auto-quote.

**Comment by thadius856** [comment]
I like the idea of a downloadable. But... then we have to update TWO things.

Does anybody know of a method to have the site generate a PDF when requested? I use a couple software suites at work that do this, but no idea how they do it.

**Comment by raysmithtx** [comment]
The Print button at the bottom of each page on the site allows the user to select either print or save as PDF.

**Comment by jkurl** [comment]
Thad,

I sent you a pm on HBT about a pre-built board that may work for the flow switch. I asked the maker if it would work with what your doing plus pointed him to your project on HBT. This pre-built board is more than what you paid but for people who don't want solder or have to build the board this may be a good option for them.

Jerry(jkurl)

**Comment by thadius856** [comment]
Thanks Jerry. I'll keep that around.

Just really wanting to get this board working. There are likely MCP23017-based pre-built boards floating around out there. I'll look into pre-built boards once we get the feature working.

**Comment by JayUnt** [comment]
@Skemp45 Can you create me a wordpress login so i can see the site?  I tried to do forgot password on jay@raspberrypints.com, and it says there is no registered user.

Thanks

**Comment by Skemp45** [comment]
No......
Just playing LOL, I will do it within the hour

**Comment by Skemp45** [comment]
@JayUnt 

Username: JayUnt
Password: was sent to your email jay@raspberrypints.com

**Comment by JayUnt** [comment]
Thanks!

On Mon, Jan 27, 2014 at 10:36 AM, Skemp45 notifications@github.com wrote:

> @JayUnt https://github.com/JayUnt
> 
> Username: JayUnt
> Password: was sent to your email jay@raspberrypints.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/60#issuecomment-33377694
> .

## 

Jason Unterman

**Comment by Skemp45** [comment]
np

**Comment by raysmithtx** [comment]
Over the next couple of weeks I have a lot of 'free' time I can devote to the project. I'm not a coder but if there's anything I can do to assist, just let me know. I'm a website guy but until we get closer with the finished project that doesn't take much time.

**Comment by thadius856** [comment]
Ray,

Please do keep going. The front page still needs quite a bit of work. Especially those 3 widgets.

Let me know if you need any direction.

Thad

**Comment by thadius856** [comment]
Skemp, can you speed up the countdown clock by 6 hours? (6 pm PST, 20 Feb 14)

**Comment by Skemp45** [comment]
Yes I can

**Comment by Skemp45** [comment]
Done

**Comment by thadius856** [comment]
Whoever was working on the website (sloe? ray?), I'll mark this one as finished once we get the homepage fleshed out. Placeholder widgets are still showing there.

**Comment by Skemp45** [comment]
FYI we have 26 NEW subscribers!!! total of 48

**Comment by thadius856** [comment]
Scherer!

**Comment by thadius856** [comment]
Skemp, is it possible to make a single page (the hardware page of the BYO section) public without exposing the rest of the site?

I'm trying to monetize our hardware selection page to offset the hosting/domain/etc costs, and maybe even get us a few pieces of test equipment if there's anything left over. HBT doesn't seem to want me posting affiliate links on their forums.

**Comment by Skemp45** [comment]
Yeah I can make that one page public I can do it after the Super Bowl

**Comment by thadius856** [comment]
The Super what?

Oh, wait. A game of handegg. Had to Google that one, phew.

No probs, man. I'll flesh it out til then.

**Comment by Skemp45** [comment]
Lol

**Comment by Skemp45** [comment]
is this the page you wanted people to be able to see? http://raspberrypints.com/site/byo/preparation/

**Comment by Skemp45** [comment]
I currently have it set so users are automatically redirected to above page. if you want it to be a different page let me know but should be good to go.

**Comment by Skemp45** [comment]
@thadius856 Can you put together a email I can blast out to our subscribers giving them the link to the parts list

**Comment by Skemp45** [comment]
you get a chance to get this done?

**Comment by thadius856** [comment]
I didn't. HBT made me take down the affiliate links anyway, so... blah, whatever. Fuck it.

**Comment by Skemp45** [comment]
We have had 53 new users since our last email blast. I feel like maybe its time to send out a new email?

**Comment by thadius856** [comment]
Sure. What do we want to say?

**Comment by Skemp45** [comment]
lets just give them a reminder of the impending release date and a link to the raspberry pints site. talk about how they can provide valuable feedback and they could see their suggestion in the next release

**Comment by thadius856** [comment]
Ugh. I forgot I have to write this tonight. _le sigh_

**Comment by thadius856** [comment]
Oops.

**Comment by thadius856** [comment]
Looks like the feature page could use some work.

**Comment by Skemp45** [comment]
62 new subscribers WOWWWWWWWWWWWW we are now almost to 200

**Comment by thadius856** [comment]
Closing because... why is this open?
